development:
  adapter: postgresql
  database: wordle_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: wordle_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: wordle_production
  pool: 5
  timeout: 5000